import keyMirror from 'keymirror'

export default keyMirror({
    GET_POSTS: null,
    FETCH_POSTS_ERROR: null,
    FETCH_MENUS_SUCCESS: null,
    FETCH_MENUS_ERROR: null,
    FETCH_SPECIALS_SUCCESS: null,
    FETCH_SPECIALS_ERROR: null,
    FETCH_CONTACTS_SUCCESS: null,
    FETCH_CONTACTS_ERROR: null,
    FETCH_CATEGORIES_INFO_SUCCESS: null,
    FETCH_CATEGORIES_INFO_ERROR: null,
    FETCH_CATEGORIES_LIST_SUCCESS: null,
    FETCH_CATEGORIES_LIST_ERROR: null,
    FETCH_PRODUCTS_LIST_SUCCESS: null,
    FETCH_PRODUCTS_COUNT_SUCCESS: null,
    FETCH_PRODUCTS_LIST_ERROR: null,
})     